### PR TITLE
Fix Empty FileCollections Error

### PR DESCRIPTION
**Pull request by efemoney**
Applying both the kotlin android plugin and the android library plugin is a typical use case.

This fails with `Empty collection can't be reduced` when you run `:kotlin-dsl-compose:metalavaCheckDebug`

### CODE REVIEW

**Comment by efemoney** [comment]
@tylerbwong Should I just fix this in this PR? It passes by replacing `reduce` with `reduceOrNull` + falling back to empty `project.files()` collection.

**Comment by efemoney** [comment]
Although the general approach to automatically picking up sourceSets from other plugins needs some work. 

`afterEvaluate` is unrecommended and introduces ordering issues, this plugin should instead be **reacting** to others being applied and not waiting until it thinks every other plugin is properly applied

**Comment by tylerbwong** [comment]
@efemoney Feel free to fix! It would be much appreciated.

Ah yea, contributions are definitely welcome in that area as it was just something I figured I'd add for convenience real quick. Would love to remove usages of `afterEvaluate`.

**Review by tylerbwong — APPROVED** [review]
Thanks for the fix!

**Comment by efemoney** [comment]
@tylerbwong needed to run `ktlintFormat`. Should be good to merge now 👍🏾

**Review by tylerbwong — APPROVED** [review]

**Comment by efemoney** [comment]
@tylerbwong will there be a release soon? this is blocking us from updating for now

**Comment by tylerbwong** [comment]
@efemoney I'll cut a release later today.

**Comment by efemoney** [comment]
Thanks!

**Pull request merged**
